### ISSUE TITLE
Tareas pendientes

### ISSUE THREAD

**Issue by olga3emes** [olga3emes/IIernaStaff#11]
- Falta favicon
- Falta ciclo Infantil
- Revisar menú hay cosas que no funcionan y los nombres tienen que estar al unísono
- Tamaño fuentes del menú
- Revisar modo móvil pantalla principal
- Añadir texto presentando a Ilerna en la pantalla principal
- Rediseñar la tarjeta de los profesores
- Revisar textos y faltas de ortografía
- Tratamiento de fotos.
-

**Comment by olga3emes** [comment]
> Listo el favicoon en todas las paginas,he mejorado el footer

María falta el favicon el en index y en voluntariado.

**Comment by MariaLopezGuillen** [comment]
He revisado, corregido y cambiado algunos nombres de los profesores que estaban incorrectos

**Comment by MariaLopezGuillen** [comment]
He rediseñado el menú para que sea funcional y estén unísono,he revisado y corregido el modo movil
